### ISSUE TITLE
Unecessary quote in test migration causes an error

### ISSUE THREAD

**Issue by andela-mabdussalam** [edcrewe/django-csvimport#104]
This quote [here](https://github.com/edcrewe/django-csvimport/blob/master/csvimport/tests/migrations/0002_country_issue98_item_organisation_unitofmeasure.py#L92) allows the migration for the test to fail.

![Screenshot 2020-07-07 at 7 55 36 AM](https://user-images.githubusercontent.com/24937734/86731320-4e694200-c027-11ea-9e35-53d865f7ad6e.png)

This should be a quick fix.

**Comment by edcrewe** [comment]
Sorry I failed to respond to your ticket.

This is a migration and as it says in the header it was generated by Django's migration tool - it is not code that was manually written by myself.

# Generated by Django 3.0.5 on 2020-05-23 11:52

So if it was failing for your test setup it may be because of your test setup or a version incompatibility. 
I have just updated the package to be compatible with latest Django 4.1.1 - this migration worked fine and all tests passed.
