### ISSUE TITLE
self.model.objects.count() throws exception on database error

### ISSUE THREAD

**Issue by rbelew** [edcrewe/django-csvimport#72]
import of a CSV file turned out to disrespect a NULL requirement of my model, and this fact was nicely captured in the `self.loglist`

	[u'Columns = Identifier, lastName, firstName, ...',
	'Using mapping from first row of CSV file',
	'Database Error: NOT NULL constraint failed: djggApp_guest.event_id, Number: 0',
	"Database Error: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block., Number: 0"]

but then trying to execute `rowcount = self.model.objects.count() - rowcount` (line#336) winds up throwing a much less informative exception: "TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block."

great project, happy to try to improve it!

**Comment by edcrewe** [comment]
Hi,

OK could replicate this with option to to not clean data and a constraint test.
So fix is to do each row insert with transaction atomic so that the post insert count works Ok.
Plus needs pre Django 1.10 check and transaction syntax backwards compatibilility option.

Be released in next version 2.6

Ed
