### ISSUE TITLE
Safe removal?

### ISSUE THREAD

**Issue by chrismp** [edcrewe/django-csvimport#89]
Hi, I'm pretty new to this. How do I safely and completely uninstall csvimport from my Django project and models?

**Comment by edcrewe** [comment]
Hi,

Remove it from the settings.INSTALLED_APPS

Remove it from urls.py - if you have added to them in one of your apps
(unlikely since it normallly just creates something via the admin UI and urls)

Create an empty migration for csvimport …

manage.py makemigrations csvimport —empty

Run that migration to delete the csvimport tables.

(If you have run the test suite then do the same for csvimport.tests to delete the test tables)

bin/pip uninstall django-csvimport

Check everything is working fine - eg. run up the django server, check that there is no longer a csvimport section in it and run tests if you have any

Thanks,
Ed

**Comment by chrismp** [comment]
`manage.py makemigrations csvimport --empty`

Gives me this error: `django.db.utils.ProgrammingError: relation "csvtests_item" does not exist
`

**Comment by edcrewe** [comment]
Hi,

OK well you must of either not run tests or run them successfully to remove test tables.

Basically its not a big deal, this is just a mechanism to auto generate table drop code but csvimport just creates a couple of tables with the prefix csvimport_ in your database anyway.
So its probably easy to just drop those tables manually via the django dbshell or your favourite db client for the db you are using.
To make sure you fully remove any install related things in your application.

Of course if you are rebuilding the database anyway with an intial migrate … it doesnt matter since the tables will no longer be rebuilt for your fresh schema once csvimport is uninstalled.

Thanks,
Ed

**Comment by chrismp** [comment]
Sorry, I meant to say:

I ran `manage.py makemigrations csvimport --empty` just fine, but when I ran `mange.py migrate`, I got that error. Also, I've already dropped all tables starting with `csvimport_` using pgAdmin. But the `migrate` error still comes up.

**Comment by edcrewe** [comment]
If you have dropped the tables, then any error like that with migrate means that 
your code still refers to csvimport somewhere or has it installed - otherwise migrate wouldnt attempt
to do migrate csvimport at all

Ed
