### ISSUE TITLE
Too many value to unpack 

### ISSUE THREAD

**Issue by nelsonyan** [edcrewe/django-csvimport#90]
Hi. Thank you for your code. I am using django 2.0.5 python 3.6.6. I was able to follow your instruction and access the CSV importer on the admin page. when I save the uploaded file. it has the error 'too many values to uppack'. I have tried to put the following into the field list: 'column1=report_key,column2=category,column3=task_name,column4=dead_line,column5=requested_by,column6=date_requested,column7=assigned_to,column8=status,column9=sku_count,column10=sell_sheet,column11=pog_render,column12=artwork_design,column13=mockup,column14=comments'
but at no avail. 
Would you please advise? I have added you as collaboartor on my repo where you can see models.py and the .csv file. Thank you and let me know if you need to see anything else

[https://github.com/nelsonyan/csvimport/invitations](url)
Request Method: | POST
-- | --
http://127.0.0.1:8000/admin/csvimport/csvimport/add/
2.0.5
ValueError
too many values to unpack (expected 2)
C:\Users\Nelson\Anaconda3\envs\mydjangoenv\lib\site-packages\csvimport\management\commands\importcsv.py in setup, line 202
C:\Users\Nelson\Anaconda3\envs\mydjangoenv\python.exe
3.6.6

**Comment by edcrewe** [comment]
Sorry this response is probably so late ... it doesnt matter anymore! But just to close the ticket ... anyway...

Thanks this error is caused with subpackaged models e.g. foo.bar.models instead of foo.models
I have fixed csvimport to handle it (in master) ... but I couldnt get your import working because its missing the referred to model from another package - models.py:from employee.models import EmployeeList
