### ISSUE TITLE
Using django-csvimport on a serverless config (app engine)

### ISSUE THREAD

**Issue by SprigganCG** [edcrewe/django-csvimport#94]
Hi,
I'm using django-csvimport on a django project with app engine. The fact is that this serverless approach blocks any file writing on the local drive in order for the app to be scalable.
Django-csvimport (admin interface import) saves the uploaded csv files in a folder on the server so it is not possible to use it 'as is' on a default app engine configuration. 
What would be the best way to desactivate/manage this file save process ? Apart from that, other functionalities of django-csvimport are working very well.

Thank you for your help!

**Comment by edcrewe** [comment]
Hi,

The problem is that the command that runs uses csvimport.parser.open_csvfile to open the saved file and check its encoding etc. So the management command assumes a file is stored somewhere.

So although it would be possible to write a handler within the parser that accepted the file contents as a string in memory and add a null file handler in the django settings, it would still need a fair amount of work for this special use case.
So sorry I know that it is possible to do this, and avoid storing anything but really the admin UI was an extra addon to what is essentially a command line utility app for Django so I regard this as out of the remit of django-csvimport. 

Instead you should address the issue by setting up a different file storage provider than the default file system storage. Since it is all abstracted in Django - csvimport should not even notice and just work as it would with the default file storage.

See https://docs.djangoproject.com/en/2.2/howto/custom-file-storage/

There are other third party packages that provide ready made alternative storage, so if you install django-storages you can use Google cloud storage as the temporary file store ...

https://django-storages.readthedocs.io/en/latest/backends/gcloud.html

... then just add a cron script to Google to wipe the files nightly or whatever you think works best for you. 

Thanks,
Ed

**Comment by SprigganCG** [comment]
Many thanks for you reply and your recommandations.
